# Generated by Django 4.2.5 on 2023-10-14 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppAromas', '0002_alter_products_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='thumbnail',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='users',
            name='rol',
            field=models.CharField(blank=True, default='/AppAromas/assets/error.png', max_length=20, null=True),
        ),
    ]
