# Generated by Django 4.2.5 on 2023-10-19 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppAromas', '0008_alter_users_options_alter_users_managers_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='rol',
            field=models.CharField(blank=True, choices=[('Basic', 'basic'), ('Admin', 'admin'), ('Staff', 'staff')], default='user', max_length=5, null=True),
        ),
    ]
