# Generated by Django 4.2.5 on 2023-10-19 05:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('AppAromas', '0009_alter_users_rol'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avatar',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='users',
            name='picture',
            field=models.ImageField(default='avatares/avatar.png', upload_to='avatares/'),
        ),
        migrations.AlterField(
            model_name='users',
            name='rol',
            field=models.CharField(blank=True, choices=[('basic', 'Basic'), ('admin', 'Admin'), ('staff', 'Staff')], default='user', max_length=5, null=True),
        ),
    ]
