# Generated by Django 4.2.5 on 2023-10-30 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppAromas', '0014_rename_qty_carts_totalcart_remove_carts_product_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carts',
            name='products',
            field=models.TextField(blank=True, null=True),
        ),
    ]
