# Generated by Django 4.2.5 on 2023-10-31 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppAromas', '0016_carts_nroinvoice'),
    ]

    operations = [
        migrations.AddField(
            model_name='carts',
            name='dateInv',
            field=models.DateField(blank=True, null=True),
        ),
    ]
